# Generated by Django 4.1.9 on 2023-06-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
