"""
Django settings for project.

Generated by 'django-admin startproject' using Django 3.2.5.
"""

import logging
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

import environ

logging.basicConfig(level=logging.INFO)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# apps/
APPS_DIR = os.path.join(BASE_DIR, "apps")
env = environ.Env()
path_env = os.path.join(BASE_DIR, '.env')
if os.path.exists(path_env):
    env.read_env(os.path.join(BASE_DIR, '.env'))

# GENERAL
SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG", False)
ENV = env("ENV")

DATETIME_FORMAT = '%d-%m-%Y %H:%M:%S'

TIME_ZONE = "UTC"
USE_TZ = True

LANGUAGE_CODE = 'en'

USE_I18N = True
USE_L10N = True

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOST", default='*').split(',')

# URLS
ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'auth.User'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # LOCAL_APPS
    'celery',
    "apps.order.apps.OrderConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("MYSQL_DATABASE"),
        "PASSWORD": env("MYSQL_ROOT_PASSWORD"),
        "HOST": env("MYSQL_HOST"),
        "PORT": env.int("MYSQL_PORT"),
        "CONN_MAX_AGE": env.int("MYSQL_CONN_MAX_AGE", default=60),
        "TIME_ZONE": TIME_ZONE,
    }
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# static setting
MEDIA_URL = '/media/'
STATIC_URL = '/static/'

# Celery settings
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"

